### ISSUE TITLE
"View it live" link does not work. 

### ISSUE THREAD

**Issue by moiAK** [Esri/precipitation-app#1]
The linked site returns the following error

This site can’t be reachedlivingatlasdev.arcgis.com’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by vannizhang** [comment]
@moiAK Thanks a lot for caching the issue. The [View it live](https://livingatlas.arcgis.com/precipitation/) link is now fixed.
